<a href="https://colab.research.google.com/github/kunalga/pythonEveryDay/blob/main/day24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
l = [1,2,3,4,4]

In [ ]:
type(l)

list

In [ ]:
a =np.array(l)

In [ ]:
a2.ndim

3

In [ ]:
a1.ndim

2

In [ ]:
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
l = [1,2,3,4,5]

In [ ]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [ ]:
a12 = a

In [ ]:
a

array([1, 2, 3, 4, 4])

In [ ]:
a[0] =10

In [ ]:
a12

array([10,  2,  3,  4,  4])

In [ ]:
import copy
original = [[1, 2], [3, 4]]
deep = copy.deepcopy(original)

deep[0][0] = 100
original[0][1] =20
print("Original:", original)  # [[1, 2], [3, 4]]
print("Deep:", deep)          # [[100, 2], [3, 4]]

Original: [[1, 20], [3, 4]]
Deep: [[100, 2], [3, 4]]


In [ ]:
np.random.rand(1,3,2)

array([[[0.06561522, 0.12294593],
        [0.02620086, 0.61086526],
        [0.79892076, 0.49506677]]])

In [ ]:
np.random.randn(1,2,2)

array([[[-1.54292249, -0.58203659],
        [-0.58908353,  1.15260916]]])

In [ ]:
ads = np.random.randint(1,10,(4,4))

In [ ]:
akf =pd.DataFrame(ads)

In [ ]:
data1 = np.random.rand(3,2,4)

In [ ]:
data1

array([[[0.94740879, 0.64675796, 0.00762274, 0.56598853],
        [0.96225895, 0.58475174, 0.40651496, 0.59436753]],

       [[0.15357854, 0.2952289 , 0.37894281, 0.59841414],
        [0.95593394, 0.8678303 , 0.17807811, 0.71013446]],

       [[0.61421462, 0.37338155, 0.93039937, 0.05164879],
        [0.82200254, 0.03677836, 0.10400379, 0.04952119]]])

In [ ]:
data1.reshape(12,2)

array([[0.94740879, 0.64675796],
       [0.00762274, 0.56598853],
       [0.96225895, 0.58475174],
       [0.40651496, 0.59436753],
       [0.15357854, 0.2952289 ],
       [0.37894281, 0.59841414],
       [0.95593394, 0.8678303 ],
       [0.17807811, 0.71013446],
       [0.61421462, 0.37338155],
       [0.93039937, 0.05164879],
       [0.82200254, 0.03677836],
       [0.10400379, 0.04952119]])

In [ ]:
data1.reshape(24,-1425)

array([[0.94740879],
       [0.64675796],
       [0.00762274],
       [0.56598853],
       [0.96225895],
       [0.58475174],
       [0.40651496],
       [0.59436753],
       [0.15357854],
       [0.2952289 ],
       [0.37894281],
       [0.59841414],
       [0.95593394],
       [0.8678303 ],
       [0.17807811],
       [0.71013446],
       [0.61421462],
       [0.37338155],
       [0.93039937],
       [0.05164879],
       [0.82200254],
       [0.03677836],
       [0.10400379],
       [0.04952119]])