<a href="https://colab.research.google.com/github/kunalga/pythonEveryDay/blob/main/day25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.logspace(1,20,100)

array([1.00000000e+01, 1.55567614e+01, 2.42012826e+01, 3.76493581e+01,
       5.85702082e+01, 9.11162756e+01, 1.41747416e+02, 2.20513074e+02,
       3.43046929e+02, 5.33669923e+02, 8.30217568e+02, 1.29154967e+03,
       2.00923300e+03, 3.12571585e+03, 4.86260158e+03, 7.56463328e+03,
       1.17681195e+04, 1.83073828e+04, 2.84803587e+04, 4.43062146e+04,
       6.89261210e+04, 1.07226722e+05, 1.66810054e+05, 2.59502421e+05,
       4.03701726e+05, 6.28029144e+05, 9.77009957e+05, 1.51991108e+06,
       2.36448941e+06, 3.67837977e+06, 5.72236766e+06, 8.90215085e+06,
       1.38488637e+07, 2.15443469e+07, 3.35160265e+07, 5.21400829e+07,
       8.11130831e+07, 1.26185688e+08, 1.96304065e+08, 3.05385551e+08,
       4.75081016e+08, 7.39072203e+08, 1.14975700e+09, 1.78864953e+09,
       2.78255940e+09, 4.32876128e+09, 6.73415066e+09, 1.04761575e+10,
       1.62975083e+10, 2.53536449e+10, 3.94420606e+10, 6.13590727e+10,
       9.54548457e+10, 1.48496826e+11, 2.31012970e+11, 3.59381366e+11,
      

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((5,5))+4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [ ]:
np.empty((2,3))

array([[3.1624792e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
a =np.eye(4)

In [ ]:
a.shape

(4, 4)

In [ ]:
a.size

16

In [ ]:
a1 = np.random.randn(2,5)

In [ ]:
a1

array([[-0.76733276,  2.3296181 , -1.32060708,  0.51212674,  0.42996907],
       [ 0.88093795,  1.29204928, -0.10341834,  1.22788577,  0.28432608]])

In [ ]:
a1[1][2]

np.float64(-0.10341833767508025)

In [ ]:
a1[0][0]

np.float64(-0.7673327602647979)

In [ ]:
m2 =np.random.randint(1,3,(3,3))

In [ ]:
m1 = np.random.randint(1,3,(3,3))

In [ ]:
m1*m2

array([[2, 4, 2],
       [4, 2, 1],
       [1, 2, 1]])

In [ ]:
m1@m2

array([[ 7, 10,  7],
       [ 5,  8,  6],
       [ 4,  6,  4]])

In [ ]:
m1

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [ ]:
pow(m1,2)

array([[4, 4, 1],
       [4, 1, 1],
       [1, 1, 1]])

In [ ]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])